apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment
  labels:
    app: centos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-app
  template:
    metadata:
      labels:
        app: centos-app
    spec:
      containers:
      - name: centos-container
        image: centos:latest
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 3600; done"]
        ports:
        - containerPort: 80
